language: php

php:
  - 7.2
  - 7.3

env:
  - SYMFONY_VERSION=3.4.*
  - SYMFONY_VERSION=4.4.*
  - SYMFONY_VERSION=5.0.*

before_script:
  - composer self-update
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/validator:${SYMFONY_VERSION}" --no-update; fi;
  - composer install --dev --no-interaction

script:
   - ./bin/phpunit --testsuite=Unit
